# Generated by Django 3.1 on 2020-08-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='device',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
